# Generated by Django 5.2.1 on 2025-05-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ra', models.CharField(max_length=8, unique=True)),
                ('turma', models.CharField(max_length=50)),
                ('trilhas', models.CharField(max_length=200)),
            ],
        ),
    ]
